######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 21 20:51:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += q_openal_export.h qalattributes.h qalbufferqueue.h qalcontext.h
SOURCES += qalattributes.cpp qalbufferqueue.cpp qalcontext.cpp
