######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 20 23:00:58 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += q_openal_export.h qalcontext.h
SOURCES += qalcontext.cpp
